import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'MOTO_SHELL_X1',
    price: 550.0,
    sku: 'SKU_JKT-001',
    category: 'CHAQUETAS',
    image: 'https://i.imgur.com/qyWhgBd.png',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    stock: 8,
  },
  {
    id: '2',
    name: 'CARGO_RIG_PRO',
    price: 320.0,
    sku: 'SKU_TRS-221',
    category: 'PANTALONES',
    image: 'https://i.imgur.com/MlElsDC.png',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    stock: 3,
  },
  {
    id: '3',
    name: 'STEALTH_BOOT_V2',
    price: 410.0,
    sku: 'SKU_FTR-990',
    category: 'CALZADO',
    image: 'https://i.imgur.com/2JX5rBN.png',
    sizes: ['38', '39', '40', '41', '42', '43'],
    stock: 12,
  },
  {
    id: '4',
    name: 'NEURAL_VIZOR',
    price: 180.0,
    sku: 'SKU_ACC-004',
    category: 'ACCESORIOS',
    image: 'https://i.imgur.com/J93H89M.png',
    sizes: ['ÚNICO'],
    stock: 4,
  },
  {
    id: '5',
    name: 'REACTOR_BACKPACK',
    price: 290.0,
    sku: 'SKU_BAG-556',
    category: 'ACCESORIOS',
    image: 'https://i.imgur.com/iWaQGF1.png',
    sizes: ['ÚNICO'],
    stock: 2,
  },
  {
    id: '6',
    name: 'GLITCH_HOODIE',
    price: 145.0,
    sku: 'SKU_SWT-112',
    category: 'CHAQUETAS',
    image: 'https://i.imgur.com/9v6kWC2.png',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    stock: 7,
  },
];

export const FEATURED_PRODUCT: Product & { specs: { label: string; value: string }[] } = {
  id: 'ft-1',
  name: 'STALKER SHELL V4',
  price: 849.0,
  sku: 'AR_CORE_STALKER',
  category: 'CHAQUETAS',
  image: 'https://i.imgur.com/Vm3ndJM.png',
  sizes: ['XS', 'S', 'M', 'L', 'XL'],
  stock: 1,
  specs: [
    { label: 'CLASE_ARMADURA', value: 'GRADO_03_TEJIDO_KEVLAR' },
    { label: 'RESIST_CLIMA', value: '100%_A_PRUEBA_TORMENTA_VOID' },
    { label: 'ENLACE_DATOS', value: 'COMPATIBLE_SYNC_NEURAL' },
    { label: 'CAP_CARGA', value: '12.5L_DISTRIBUIDO' },
  ],
};

export const REVIEWS = [
  {
    id: 'r1',
    user: 'GHOST_RAIDER',
    rank: 'ELITE',
    rating: 5,
    text: 'LA INTEGRACIÓN DEL HUD EN LOS PANTALONES CARGO ES PERFECTA. SOBREVIVÍ AL COLAPSO DEL SECTOR 7 SIN UN RASGUÑO.',
  },
  {
    id: 'r2',
    user: 'NEON_KNIGHT',
    rank: 'VETERANO',
    rating: 4,
    text: 'LA TECNOLOGÍA DE LA TELA ES INIGUABLE. EL ÚNICO PROBLEMA ES EL TIEMPO DE RECARGA DE LAS COSTURAS DE NEÓN.',
  },
  {
    id: 'r3',
    user: 'NULL_PTR',
    rank: 'OVERSEER',
    rating: 5,
    text: 'VOID/WEAR ES LA ÚNICA MARCA EN LA QUE CONFÍO CUANDO EL SISTEMA SE OSCURECE. BRUTALISMO FUNCIONAL PURO.',
  },
];
